/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutPrivacyPolicyImport } from './routes/_layout/privacy-policy'
import { Route as LayoutLegalImport } from './routes/_layout/legal'
import { Route as LayoutContentGuidelinesImport } from './routes/_layout/content-guidelines'
import { Route as LayoutOnboardingCreatorImport } from './routes/_layout/onboarding/creator'
import { Route as LayoutAuthSignInImport } from './routes/_layout/auth/sign-in'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutPrivacyPolicyRoute = LayoutPrivacyPolicyImport.update({
  path: '/privacy-policy',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutLegalRoute = LayoutLegalImport.update({
  path: '/legal',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutContentGuidelinesRoute = LayoutContentGuidelinesImport.update({
  path: '/content-guidelines',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutOnboardingCreatorRoute = LayoutOnboardingCreatorImport.update({
  path: '/onboarding/creator',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAuthSignInRoute = LayoutAuthSignInImport.update({
  path: '/auth/sign-in',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/content-guidelines': {
      id: '/_layout/content-guidelines'
      path: '/content-guidelines'
      fullPath: '/content-guidelines'
      preLoaderRoute: typeof LayoutContentGuidelinesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/legal': {
      id: '/_layout/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LayoutLegalImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/privacy-policy': {
      id: '/_layout/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof LayoutPrivacyPolicyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/auth/sign-in': {
      id: '/_layout/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof LayoutAuthSignInImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/onboarding/creator': {
      id: '/_layout/onboarding/creator'
      path: '/onboarding/creator'
      fullPath: '/onboarding/creator'
      preLoaderRoute: typeof LayoutOnboardingCreatorImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  LayoutRoute: LayoutRoute.addChildren({
    LayoutContentGuidelinesRoute,
    LayoutLegalRoute,
    LayoutPrivacyPolicyRoute,
    LayoutIndexRoute,
    LayoutAuthSignInRoute,
    LayoutOnboardingCreatorRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/content-guidelines",
        "/_layout/legal",
        "/_layout/privacy-policy",
        "/_layout/",
        "/_layout/auth/sign-in",
        "/_layout/onboarding/creator"
      ]
    },
    "/_layout/content-guidelines": {
      "filePath": "_layout/content-guidelines.tsx",
      "parent": "/_layout"
    },
    "/_layout/legal": {
      "filePath": "_layout/legal.tsx",
      "parent": "/_layout"
    },
    "/_layout/privacy-policy": {
      "filePath": "_layout/privacy-policy.tsx",
      "parent": "/_layout"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/auth/sign-in": {
      "filePath": "_layout/auth/sign-in.tsx",
      "parent": "/_layout"
    },
    "/_layout/onboarding/creator": {
      "filePath": "_layout/onboarding/creator.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
